version: 2.1

parameters:
  nombre:
    type: string
    default: juank-pipeline-default

jobs:
  sayhello:
    parameters:
    nombre:
      type: string
      default: juank-job-default
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo hola << parameters.nombre >>

workflows:
  workflow1:
    jobs:
      - sayhello:
          nombre: juank