version: 2.1

commands:
  giveme-time-and-wait:
    steps:
      - run: date && sleep 10

jobs:
  say-hello:
    docker:
      - image: ubuntu:latest
    steps:
      - giveme-time-and-wait
      - run: echo hola
      - giveme-time-and-wait
  say-bye:
    docker:
      - image: cimg/base:stable
    steps:
      - giveme-time-and-wait
      - run: echo Byeee
      - giveme-time-and-wait

workflows:
  workflow1:
    jobs:
      - say-hello
      - say-bye

