version: 2.1

parameters:
  nombre:
    type: string
    default: juank

jobs:
  sayhello:
    parameters:
    nombre:
      type: string
      default: juankjob
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo hola << pipeline.parameters.nombre >>

workflows:
  workflow1:
    jobs:
      - sayhello